baseURL = "https://millionhz.github.io/"
languageCode = "en-us"
title = "Network Security"
theme = 'hugo-book'
canonifyURLs = true
enableGitInfo = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'auto'
  BookRepo = 'https://github.com/millionhz/network-security-notes'
  BookEditPath = 'edit/main'
